### PR TITLE
DAT-3636: added logic which helps clean up generated tag for sequence

### PR DESCRIPTION
**Pull request by achehrynets**

### CODE REVIEW

**Review by SteveDonie — COMMENTED** [review]
Looks OK. Note the change to the Database interface which could have impacts on any implementations of that interface, especially outside of the main codebase.

**Review by wwillard7800 — COMMENTED** [review]
In your changes to the getSelectSequenceSql(Object value, Database database) method, you removed a block of comments, and then refactored the code to remove several CASE statements.  So that I understand, what was the purpose of doing this?  Do the comments live somewhere else now?  Is the logic of the CASE statements not needed now?

**Comment by achehrynets** [comment]
> In your changes to the getSelectSequenceSql(Object value, Database database) method, you removed a block of comments, and then refactored the code to remove several CASE statements. So that I understand, what was the purpose of doing this? Do the comments live somewhere else now? Is the logic of the CASE statements not needed now?

Let's understand the problem which exists.
Previous state of query which retrieves data about sequences for Oracle returns default value for attributes like `START_VALUE`, `CACHE_SIZE`, `INCREMENT_BY` and etc  as `NULL`. Seems like it was added for logic which cleans up generated changelog file from default values, because RDBMS adds it by own self. 
And here is root cause of problem. It works correctly for `generateChangeLog` and `snapshot`, but it does not work for diff functionality at all, because query which retrieves `NULL` for default values affects metadata and we faced with case when running through diff functionality where one of databases has sequence with all attributes are default and second database had randomly generated values for sequence attribute, we got `alterSequence` tag which showed only `sequenceName` attribute, but should all sequence attributes.
I decided to remove logic for `clean up generated changelog file` from snapshot layer and moved it to `MissingChangeGenerator` layer. It is most applicable way which helps save `snapshot` and `diff` functionality. 

About deleted comments, I just removed it and did not think about any impact.
But I think it is good idea to return it, seems like most applicable place is `OracleDatabase#getDefaultValuesForSequence` method, because I used links from comment, as the place where I could found default value for oracle sequence attributes.

**Comment by wwillard7800** [comment]
Thank you, Andrii.  That clears it up for me.

**Comment by nvoxland** [comment]
With the changes to the database interface, and the fact that it's an example of a general problem and not a complete solution, it's not a change we'd want to bring into a release yet. But it's fine for the DAT-1999 branch.

**Review by nvoxland — APPROVED** [review]

**Pull request merged**
