### PR TITLE
Fixed Oracle: Index out of bounds error from generateChangeLog of a c…

### PR DESCRIPTION
**Pull request by odemk**
…ross-schema foreign key.

### CODE REVIEW

**Comment by SteveDonie** [comment]
@odemk can you please write a short description of what the issue was and what the fix was, and add that to this pull request?

**Comment by nvoxland** [comment]
From talking with him, the problem is that a change we made a while ago for performance reasons is breaking the cross-schema FK snapshots. It used to be that we would snapshot objects one schema at a time, and so when you'd find an object in a schema you hadn't seen before you would know it is an external schema and you need to snapshot that object too.

But, the change we made was to sometimes note all the schemas they will want to snapshot and then pull down all the objects in all the schemas in a single query. The bulkReturnsAllSchemas method that was changed is supposed to say whether all the schemas have been queried and so anything we don't see we can assume doesn't exist. The optimization logic relies on the bulkReturnsAllSchemas value to control code paths to go down.

The problem was introduced because now when you hit the "get all the objects in all the schemas" optimization path, it wasn't correctly handing the case when we start finding even more schemas we need to snapshot objects from. It is assuming that it just doesn't exist since it's supposed to have all the schemas.

**Comment by nvoxland** [comment]
We get into the optimization path by setting the list of all the schemas to snapshot in the getAllCatalogsStringScratchData, so this fix would be improving the bulkReturnsAllSchemas logic to only say it returned all schemas if we have the data in getAllCatalogsStringScratchData that would cause us to get all the schemas.

It's a good thing to change because I think it makes the logic of bulkReturnsAllSchemas better, but I'm worried it doesn't actually fix the problem completely.

My guess is that the fix handles the case where we're snapshotting a single schema and so aren't in the multi-schema optimization but that if we have a multi-schema snapshot with FKs that span schemas we'll still have the bug because bulkReturnsAllSchemas will go back to returning true.

**Comment by SteveDonie** [comment]
Thanks! Something like that is exactly what I was hoping to capture.

**Comment by odemk** [comment]
@nvoxland , thanks for explaining the issue to @SteveDonie.

I've extended the fix for a case when we have a multi-schema snapshot and a FK is in none of them.

**Comment by nvoxland** [comment]
That looks like a better fix, thanks!

**Pull request merged**
