### PR TITLE
[DAT-12494] Fix issue with Postgres sequences

### PR DESCRIPTION
**Pull request by andrulban**
1. Logic to check if sequence is automatically generated is added to be able to understand if column type is serial or it is not serial, but just uses sequences (PgDatabaseMetaData replaces this info by default)
2. Query to check dependencies for Postgres was edited to order by objid and LinkedHashMap was used instead of HashMap for nodes at DependencyGraph to keep ordering for query. (This is needed for Postgres query because DB does not see dependencies between table and sequence, so when order is defined orphan nodes has wrong ordering because HashMap does not preserve order in which elements were added into it)

### CODE REVIEW

**Review by achehrynets — APPROVED** [review]

**Review by RomanDeveloperAcc — APPROVED** [review]

**Comment by nvoxland** [comment]
It's not immediately obvious to me what the changes end up doing, since the postgresql metadata queries are complex and I don't know what they end up corresponding to.

We ended up having to rely less on "sequence is owned on the table" in liquibase/liquibase#3335 . But I don't know if "owned by" is different than the dependency columns? 

I'm also not sure why the HashMap -> LinkedHashMap and the "order by dependency id" had to be made? I think the map is more a pile of dependency connections, and then there is a separate process that takes that unsorted pile and builds up the actual dependency tree? If it matters the ordering of the raw map I wonder if that's hiding a deeper problem?

**Comment by achehrynets** [comment]
> It's not immediately obvious to me what the changes end up doing, since the postgresql metadata queries are complex and I don't know what they end up corresponding to.
> 
> We ended up having to rely less on "sequence is owned on the table" in [liquibase#3335](https://github.com/liquibase/liquibase/pull/3335) . But I don't know if "owned by" is different than the dependency columns?
> 
> I'm also not sure why the HashMap -> LinkedHashMap and the "order by dependency id" had to be made? I think the map is more a pile of dependency connections, and then there is a separate process that takes that unsorted pile and builds up the actual dependency tree? If it matters the ordering of the raw map I wonder if that's hiding a deeper problem?

@andrulban is on PTO, so I'll say what I know.

The query which tries determine dependencies between database objects does not return/have information about all dependent objects
e.g. it does not see dependencies between table column and sequence created for this column in some cases
As the result, sequence may be created prior table in snapshot but it's not correct
P.s. @andrulban will add details later

Andrii T added sorting to the query just to keep ordering of deployed changes as is and it helps in case when we have lack of information about dependent objects and makes correct order of changes in generated snapshot/diff.

Next part of determination of dependent objects for postgres (logic which builds dependency tree) is our custom logic which relies on result set of the query. 
And in case when it cannot determine dependencies between object because result set does not have information then we need to keep ordering returned by query with sorting and LinkedHashMap helps with it.

There are a couple of use cases with sequences which are covered by changes:
1. Sequence was automatically created by a database because column type is SERIAL
2. Sequence was created by a user manually and then used in a table column
And maybe more scenarios which I don't remember

So, saving order of deployed changes + keeping order when building dependency tree does trick when we cannot get all information about dependent object, but I should mention that problems fixed with those changes are edge cases because the logic which builds dependency tree handles most of usual cases. 
And it least one edge cases with sequences we faced, but there can be more.

**Comment by nvoxland** [comment]
> The query which tries determine dependencies between database objects does not return/have information about all dependent objects
> e.g. it does not see dependencies between table column and sequence created for this column in some cases
> As the result, sequence may be created prior table in snapshot but it's not correct

The dependencies between a sequence and a column is the part that's a bit fuzzy in my mind in general for postgresql so makes it hard for me to say "yes, this is good" or "no, it has problems". I don't know how "owned" is tracked vs. "used for auto-increment" and I used to think those were the same but https://github.com/liquibase/liquibase/pull/3335 showed they are different. So at least asking if we are checking the right dependency metadata.

The dependency tree logic is always a lot of magic to me too and takes a bit of debugging to re-remember how it all works, and even then it's always a bit rough in my mind. It's a lot of code copied from stackoverflow and then later work-arounds. And what's in this branch is probably a bit different at this point than what's in master which I know better. So sorting it works better, that's the main thing. It seems surprising that it would make a difference, but lots of things surprise me in that code :)

**Comment by andrulban** [comment]
Hi @nvoxland , I am back from PTO :)
So, regarding this fix - this issue is also present at community version, I will try to describe an issue by steps and why Liquibase team might have missed it in your tests (flakiness)... So there are multiple issues:
1. Case: We manually create sequence and use it as default value for a key column. We make a snapshot and our snapshot will create a table with serial type for a key and sequence (ordering of chageSets is flaky because of HashMap)
2. SQL which we use to get dependencies for Postgres does not see dependency between sequence which is manually created and is NOT owned by column by which it is used

So when you make a snapshot, create second db based on this snapshot and make a diff you will see that there are differences.

We have multiple cases here:
1. In changeLog after snapshot we have a table first and sequence later (this is flaky) and sequence which we created has the same name which would be created for serial (e.g. you have a TABLE category with category_id as key column and sequence with name category_category_id_seq), then you won't have duplicates because during sequence creation Postgres will just warn that such sequence already exists. (IMPORTANT sequence is not owned by the column which uses it)
2. Same case as previous, but in change log sequence is created first, then we will end up with two sequences and only the second one will be used by the key column and the second sequence will be named with 1 at the end (e.g. category_category_id_seq1)
3. If sequence name is not "default", e.g. custom_seq, then there is no chance it will be used by the newly created table... We will end up with two sequences custom_seq and category_category_id_seq. category_category_id_seq will be used by newly created table. So custom sequences, which are not owned by the key using it, are never used after snapshot->deploy operation...

**Pull request merged**
