### PR TITLE
Handle case for db2 when schemas have same name but different case

### PR DESCRIPTION
**Pull request by riakivets**

### CODE REVIEW

**Comment by riakivets** [comment]
I run unit testes;
I did manual testing;
I'm going to run some liquibase cucumber tests and update the comment here

**Comment by riakivets** [comment]
Please don't review yet. I'm going to add a fix in scope of this ticket !

**Comment by nvoxland** [comment]
I worry about forcing quoting of the catalogs like you are, because most times people type them in as lower case and expect them to not be quoted and so be case insensitive.

Without that part of the fix, does the fix not work?

**Comment by riakivets** [comment]
In general this fix only for DB2
For other DBs it will work as is.
Without that part of the fix, does the fix not work? -- No

IF catalog not  quoted it's doesn't work !
e.g. If you have schemas in db2
let's say testing or TESTING or TeSTinG
Those different sachems. Will be executed in different way:
CREATE TABLE "testing"."t1" ("COLUMN1" CLOB);
CREATE TABLE "TESTING "."t1" ("COLUMN1" CLOB);
CREATE TABLE "TeSTinG"."t1" ("COLUMN1" CLOB);
without quotes 
everything will go to TESTING 

What do you thing about it ?

**Comment by nvoxland** [comment]
Saw it was only for DB2, but worried it will break normal db2 usage.

People like to put:

<createTable catalogName="testing" tableName="t1" > 

and expect it to create it as "create table testing.t1" without quotes because things should not be case sensitive in a database. But your fix breaks that use case, right? The generated SQL will always have quotes and so not do what people expect.

There is a quoteAllObjects attribute that can be set on the changeSet or the changeLog to put quotes in if they really want them, but the default for that is false. 

Is the original caused by not respecting and/or setting the quoteAllObjects flag?

**Comment by riakivets** [comment]
I need to check this but there are 3 issues:
1. Original logic always applies schema.toUpperCase() for DB2
2. if quoteAllObjects = true it won't help because of point 1
3. if schema testing and TESTING exist I can't create a change log because of error that duplication found because logic 1.

Maybe I need to revert logic that does quoting but leave the schema comparison(equals original names)
and try to set quoteAllObjects  = true
What do you thing about this plan ?
If it's ok I'll check this and inform you about result.

**Comment by nvoxland** [comment]
Yes, try taking out the quoting changes but leave the case-sensitive naming equality in there and see if that still resolves the issue.

**Comment by riakivets** [comment]
@nvoxland  thanks. 
It make sense for me. I'll check it out !

**Comment by riakivets** [comment]
@nvoxland,   I took out quoting changes and tested logic. The issue wan't resolved. 
1. When I wanted to initialize Liquibase project where DB has 2 schemas: TESTING, testing
I got an error 
```
14:45:53.778 [ModalContext] WARN  c.d.h.c.m.LiquibaseSchemaMigrationService - liquibase.exception.DatabaseException: The name of the object to be created is identical to the existing name "TESTING.DATABASECHANGELOG" of type "TABLE".. SQLCODE=-601, SQLSTATE=42710, DRIVER=3.72.30 [Failed SQL: CREATE TABLE testing.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(4000), LABELS VARCHAR(4000), DEPLOYMENT_ID VARCHAR(10))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:364)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:119)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:103)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:240)
	at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1142)
	at liquibase.Liquibase.changeLogSync(Liquibase.java:826)
	at com.datical.hammer.core.migration.LiquibaseSchemaMigrationService.syncChangelog(LiquibaseSchemaMigrationService.java:402)
	at com.datical.db.ui.jobs.ChangeLogSyncJob$ChangeLogSyncOperation.run(ChangeLogSyncJob.java:172)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: The name of the object to be created is identical to the existing name "TESTING.DATABASECHANGELOG" of type "TABLE".. SQLCODE=-601, SQLSTATE=42710, DRIVER=3.72.30
	at com.ibm.db2.jcc.am.hd.a(hd.java:813)
	at com.ibm.db2.jcc.am.hd.a(hd.java:66)
	at com.ibm.db2.jcc.am.hd.a(hd.java:140)
	at com.ibm.db2.jcc.am.kp.c(kp.java:2788)
	at com.ibm.db2.jcc.am.kp.d(kp.java:2776)
	at com.ibm.db2.jcc.am.kp.b(kp.java:2154)
	at com.ibm.db2.jcc.t4.bb.j(bb.java:233)
	at com.ibm.db2.jcc.t4.bb.c(bb.java:48)
	at com.ibm.db2.jcc.t4.p.b(p.java:38)
	at com.ibm.db2.jcc.t4.vb.h(vb.java:124)
	at com.ibm.db2.jcc.am.kp.ib(kp.java:2149)
	at com.ibm.db2.jcc.am.kp.a(kp.java:3322)
	at com.ibm.db2.jcc.am.kp.e(kp.java:1105)
	at com.ibm.db2.jcc.am.kp.execute(kp.java:1084)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:362)
	... 9 more
```

2. When I wanted to get status I've another error

```
Failed to get Liquibase Change Set Statuses (The name of the object to be created is identical to the existing name "TESTING.DATABASECHANGELOG" of type "TABLE".. SQLCODE=-601, SQLSTATE=42710, DRIVER=3.72.30 [Failed SQL: CREATE TABLE testing.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(4000), LABELS VARCHAR(4000), DEPLOYMENT_ID VARCHAR(10))])
	at com.datical.hammer.core.status.DaticalStatusService.getStatus(DaticalStatusService.java:64)
	at com.datical.db.ui.editors.DbStatusEditor.getChangeSetStatus(DbStatusEditor.java:1027)
	at com.datical.db.ui.editors.DbStatusEditor.updateTableInput(DbStatusEditor.java:992)
	at com.datical.db.ui.editors.DbStatusEditor.updateOnSwitchPage(DbStatusEditor.java:973)
	at com.datical.db.ui.contributors.StatusPageContribution.setupForStatusPage(StatusPageContribution.java:122)
	at com.datical.db.ui.contributors.StatusPageContribution.switchToPage(StatusPageContribution.java:89)
	at com.datical.db.ui.editors.DbSectionBuilder.updateStatusPage(DbSectionBuilder.java:682)
	at com.datical.db.ui.editors.DbSectionBuilder.updatePages(DbSectionBuilder.java:671)
	at com.datical.db.ui.editors.DbSectionBuilder.getStatus(DbSectionBuilder.java:1107)
	at com.datical.db.ui.editors.DbSectionBuilder$6$1.run(DbSectionBuilder.java:539)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at com.datical.db.ui.editors.DbSectionBuilder$6.widgetSelected(DbSectionBuilder.java:535)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:240)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4165)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3754)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at com.datical.db.ui.DaticalApplication.start(DaticalApplication.java:81)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
Caused by: liquibase.exception.DatabaseException: The name of the object to be created is identical to the existing name "TESTING.DATABASECHANGELOG" of type "TABLE".. SQLCODE=-601, SQLSTATE=42710, DRIVER=3.72.30 [Failed SQL: CREATE TABLE testing.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(4000), LABELS VARCHAR(4000), DEPLOYMENT_ID VARCHAR(10))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:364)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:119)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:103)
	at liquibase.changelog.StandardChangeLogHistoryService.init(StandardChangeLogHistoryService.java:240)
	at com.datical.hammer.core.migration.DaticalLiquibaseServiceImpl.initializeLiquibaseTables(DaticalLiquibaseServiceImpl.java:350)
	at com.datical.hammer.core.status.DaticalStatusService.getStatus(DaticalStatusService.java:58)
	... 36 more
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: The name of the object to be created is identical to the existing name "TESTING.DATABASECHANGELOG" of type "TABLE".. SQLCODE=-601, SQLSTATE=42710, DRIVER=3.72.30
	at com.ibm.db2.jcc.am.hd.a(hd.java:813)
	at com.ibm.db2.jcc.am.hd.a(hd.java:66)
	at com.ibm.db2.jcc.am.hd.a(hd.java:140)
	at com.ibm.db2.jcc.am.kp.c(kp.java:2788)
	at com.ibm.db2.jcc.am.kp.d(kp.java:2776)
	at com.ibm.db2.jcc.am.kp.b(kp.java:2154)
	at com.ibm.db2.jcc.t4.bb.j(bb.java:233)
	at com.ibm.db2.jcc.t4.bb.c(bb.java:48)
	at com.ibm.db2.jcc.t4.p.b(p.java:38)
	at com.ibm.db2.jcc.t4.vb.h(vb.java:124)
	at com.ibm.db2.jcc.am.kp.ib(kp.java:2149)
	at com.ibm.db2.jcc.am.kp.a(kp.java:3322)
	at com.ibm.db2.jcc.am.kp.e(kp.java:1105)
	at com.ibm.db2.jcc.am.kp.execute(kp.java:1084)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:362)
	... 42 more
```
3. I event didn't try to update change log with some changeSet to specify QuotingStrategy.
 In general, problem that even basic queries with checks to DB2 where we have the same schemas but diff case generate errors if those not quoted

@nvoxland Please let me know what do you think about it ?
More ideas ?

**Comment by nvoxland** [comment]
Could you make it so that just those liquibase calls force the quoting? 

Otherwise: I'm wondering if it's enough of an edge case that we shoudn't bother with it right now? There is a lot of vagueness in how liquibase handles case sensitivity that I'm hoping to revisit in general over the next few months and perhaps we should just leave it as is for now and fix it in general at that point?

**Comment by nvoxland** [comment]
Thinking more, I'm not sure we even want to force the quoting of liquibase calls, since people want to put "defaultSchemaName=test" and not have to match case.

I'm thinking more that this may be something that is a larger problem that should be handled in the general case with a major liquibase release, rather than something we're trying to patch. 

Unless it is something customers are actually running into?

**Comment by riakivets** [comment]
Unless it is something customers are actually running into? Yes

**Comment by nvoxland** [comment]
OK. May need to handle it sooner, then. I'll do a little debugging and see if I see a good way to sneak a fix in without affecting normal use as much.

**Comment by riakivets** [comment]
> Could you make it so that just those liquibase calls force the quoting?

In general yes. But we have a lot cases where we need to do this. And each case will be stub. I think this approach wrong.

**Comment by riakivets** [comment]
@nvoxland, My thinking 

> I'm not sure we even want to force the quoting of liquibase calls, since people want to put "defaultSchemaName=test" and not have to match case.
It's true. But case when we have the same schema names but just diff case also also present :-)

@nvoxland What I should do for now ?

**Comment by nvoxland** [comment]
Yes, that is the problem: 95% of the time, people want to treat sql objects names case insensitively and so we want to be case insenstive. But 5% of the time, they do care and we can't break with that. 

That is why we have the quoteObjectNames attribute to let you control quoting within a changeSet and enable it if you really want it. But it looks like this problem isn't within a changeset: it's in the queries liquibase is making to check the databasechangelog and databasechangelog lock tables. 

The quotingStrategy ends up being controlled on the Database.quotingStrategy field, so we can set that to QUOTE_ALL_OBJECTS before making the liquibase calls and then back to what it was before, but we'd need a way to know when to enable that. I thought for a bit about checking the database for schemas with the same name but different cases and automatically setting it when there was a conflict, but we should try to avoid all database interactions if possible. Otherwise we break offline support or updateSql-style support.

So, I think at the Liquibase level, we have to rely on being told to quote them, like we do in changeSets. We can add a new quoteLiquibaseObjects command line argument that will need to be stored somewhere that the liquibase-change-generating classes like StandardChangeLogHistoryService can get to it and know to set quotingStrategy=QUOTE_ALL_OBJECTS before doing operations, and then set it back when it's done.

I'm going to be traveling today, so can't do much to look at it until tonight. See if you can find a good way add and use that new quoteLiquibaseObjects parameter.

**Comment by neupsh** [comment]
@riakivets, @nvoxland , @wwillard7800 
I have commmented 3 lines of code in `DaticalLiquibaseServiceImpl.java` line 422 to make the builds pass. They were failing as this pull request has not been merged yet. **Whoever merges this ticket, please update the pom.xml for this liquibase version and also uncomment the following code lines (if block) from that class, and remove that shouting comment from there as well :**
```
// NOTE: BUG BUG BUG BUG THIS IS DEPENDENT ON LIQUIBASE CHANGE WHICH IS NOT MERGED YET!
    // COMMENTING THIS TO MAKE BUILDS PASS. PLEASE UNCOMMENT THE FOLLOWING COMMENTED 3 LINES OF CODE AFTER
    // https://github.com/Datical/liquibase/pull/27 HAS BEEN MERGED
    /*if (CatalogAndSchema.CatalogAndSchemaCase.ORIGINAL_CASE.equals(database.getSchemaAndCatalogCase())) {
      trackingSchemaName = "\"".concat(trackingSchemaName).concat("\"");
    }*/
```

**Pull request merged**
