### PR TITLE
DAT-3644: Updated RegExp to take into account that date value during

### PR DESCRIPTION
**Pull request by achehrynets**
workflow could comes as `TO_DATE`

### CODE REVIEW

**Review by SteveDonie — APPROVED** [review]

**Review by wwillard7800 — COMMENTED** [review]
@achehrynets 
https://www.crcind.com/csp/docbook/DocBook.UI.Page.cls?KEY=RSQL_todate
Oracle also supports TODATE().  Do we need to take this into consideration?

**Comment by achehrynets** [comment]
>  Do we need to take this into consideration?

@wwillard7800 
I did testing to double check this case and I would like to say that we do not need to carry about this one, because when liquibase sees that date value comes as `to_date/TO_DATE(`, it generates changelog and gets date value as is and in generated changelog we will see attribute `defaultValueComputed` unlike `defaultValueDate` and it is correct.

A bit more about testing.
I created DDL like:
`CREATE TABLE "TEST_TABLE"
(	"ID" NUMBER NOT NULL ENABLE,
   "TEST_DATE" DATE DEFAULT '01-JAN-2020',
   "TEST_DATE1" DATE DEFAULT to_date('2020-01-01', 'yyyy-MM-dd'),
   "TEST_DATE2" DATE DEFAULT TO_DATE('2020-01-01', 'yyyy-MM-dd'),
   "TEST_DATE3" DATE DEFAULT to_date('20200101', 'yyyyMMdd'),
   "TEST_DATE4_NULL" DATE DEFAULT NULL,
   "TEST_TIMESTAMP" TIMESTAMP DEFAULT '26-JUN-02 09:39:16.78',
   "TEST_TIMESTAMP1" TIMESTAMP DEFAULT to_date('2020-01-02 09:39:16', 'YYYY-MM-DD HH24:MI:SS'),
   "TEST_TIMESTAMP2" TIMESTAMP DEFAULT TO_DATE('2020-01-02 09:39:16', 'YYYY-MM-DD HH24:MI:SS'),
   "TEST_TIMESTAMP3" TIMESTAMP DEFAULT TO_DATE('2020/01/02 09:39', 'YYYY/MM/DD HH24:MI'),
   "TEST_TIMESTAMP4" TIMESTAMP DEFAULT to_date('2020/01/02 09:39', 'YYYY/MM/DD HH24:MI'),
   "TEST_TIMESTAMP5_NULL" TIMESTAMP NULL,
   "TEST_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "TEST_TIME1" TIMESTAMP DEFAULT to_date('09:39:16', 'HH24:MI:SS'),
   "TEST_TIME2" TIMESTAMP DEFAULT TO_DATE('09:39:16', 'HH24:MI:SS'),
   "TEST_TIME3" TIMESTAMP DEFAULT TO_DATE('09:39', 'HH24:MI'),
   "TEST_TIME4_NULL" TIMESTAMP DEFAULT NULL,
  CONSTRAINT "ID_CONSTR" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  ENABLE
);`

And went through `snapshot` and `diff` functionality. I followed plan like:
1. Apply DDL on primary database.
2. Generate changelog through primary database. 
3. Apply generated changelog from step #2 to secondary database instance.
4. Run diff between primary and secondary databases.
And finally, I got empty diffchangelog.

**Review by wwillard7800 — APPROVED** [review]
Thanks for the update.

**Comment by nvoxland** [comment]
So the end fix for this ended up just being a fix to handle different capitalization when trying to recognize the to_date function? 

Rather than having checks for TO_DATE and to_date explicitly, we should be doing the check case insensitively, so we don't fail still with To_Date(). Either use the case insensitive flag on the regular expression, or do `value.toUpper().matches(....)`

**Review by nvoxland — CHANGES_REQUESTED** [review]
(see comment above, github makes me put this in)

**Comment by achehrynets** [comment]
> So the end fix for this ended up just being a fix to handle different capitalization when trying to recognize the to_date function?
> 
> Rather than having checks for TO_DATE and to_date explicitly, we should be doing the check case insensitively, so we don't fail still with To_Date(). Either use the case insensitive flag on the regular expression, or do `value.toUpper().matches(....)`

agreed, I updated implementation.

**Review by nvoxland — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
